server:
  port: 0

spring:
  application:
    name: user

eureka:
  instance:
    instance-id: ${spring.application.instance:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
