spring:
  profiles:
    active: dev
  cloud:
    config:
      name: user-service
  config:
    import: configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
      show-details: always

temp:
  name: temp
  money: 2000

