server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  #    driver-class-name: org.h2.Driver
#    username: sa
#    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

eureka:
  instance:
      instance-id: ${spring.application.name}:${random.value}
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.example.orderservice: info
