server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BJP-Learning-Space/MSA-Study
          search-paths: /config
          default-label: master
#          uri: file:///Users/qjawlsqjacks/Projects/MSA-Study
#          search-paths: /config
#          default-label: master

